version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: lu97is/nonubereats-frontend
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Building docker image
          command: |
            docker build -t $IMAGE_NAME:latest -f Dockerfile.dev .
      - run:
          name: Testing docker image
          command: |
            docker run -e CI=true $IMAGE_NAME npm test 
      - run:
          name: Publish image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin docker push $IMAGE_NAME:latest
