version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: lu97is/nonubereats
      IMAGE_NAME_PROD: lu97is/nonubereats-frontend
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Building docker image
          command: |
            docker build -t $IMAGE_NAME:latest -f Dockerfile.dev .
      - run:
          name: Testing docker image
          command: |
            docker run -e CI=true $IMAGE_NAME npm test
  deploy:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Minified version and deploy
          command: |
            docker build -t $IMAGE_NAME_PROD:latest --build-arg FIREBASE_AUTH_TOKEN=$FIREBASE_AUTH_TOKEN .
      - run:
          name: Login to docker
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Publish to docker
          command: |
            docker push $IMAGE_NAME_PROD
workflows:
  version: 2
  build-master:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
    
      
